### ISSUE TITLE
[Compat] Please depend on NBT Crafting

### ISSUE THREAD

**Issue by supersaiyansubtlety** [DashEightMate/flamin-hot#1]
I'm the dev of [Automated Crafting](https://www.curseforge.com/minecraft/mc-mods/automated-crafting). A user reported an issue between Flamin' Hot and automated crafting, and it appears to be because Automated crafting isn't aware of custom recipes that return items to the crafting grid. 

Please consider using [NBT Crafting](https://www.curseforge.com/minecraft/mc-mods/nbt-crafting) (or another recipe mod if you prefer) for your custom recipes. This would make it so other mods like mine that have crafters don't have to support flamin hot in particular (and any other mod with its own custom crafting modifications) and instead only have to support one to several crafting libraries. 

I believe you could use NBT Crafting to achieve your current recipe behavior similarly to [this example](https://mcwiki.siphalor.de/nbt-crafting/v2/#dynamic-data/dollars/~example). If you created a tag for all blocks for which you intend to allow fire-resistance modification and use nbtc's dollars system, you should be able to increment/decrement your blocks' nbts the same way you do in [ItemModRecipe](https://github.com/DashEightMate/flamin-hot/blob/master/src/main/java/com/dasheightmate/flaminhot/recipes/ItemModRecipe.java#L79).

Also, I'd consider outputting to the actual output rather than returning items to the crafting grid. I realize this would require all blocks being modified to be of the same type+nbt, but it's simpler and more inline with vanilla, and therefore more intuitive. 

(Also just me being a pedant but [this if...else if... chain](https://github.com/DashEightMate/flamin-hot/blob/master/src/main/java/com/dasheightmate/flaminhot/recipes/ItemModRecipe.java#L84) is exactly what switch cases are for. )

**Comment by marshoepial** [comment]
Thanks for letting me know about this. I had assumed that implementing CraftingRecipe meant mods could use it like a vanilla crafting recipe. Not so, apparently.

I took a look at NBT Crafting and it looks promising, but there are a couple things keeping me from using it. First, I want all blocks to be able to be targeted by my mod. It doesn't make sense to fireproof cobblestone, but later you'll be able to make it flammable, or give it infiniburn, etc (I haven't gotten around to implementing that though :P). Doing this would mean creating a tag for every block at runtime - not impossible, but it's yet another lib and a bit of an ugly solution. 

The other issue is that I've heard that NBT Crafting is pretty unstable still - I haven't used it personally before, but some others have told me that it can be pretty buggy. I'd like to avoid something that could create a lot of instability like that. Feel free to correct me on that if I'm wrong.

I'd like to work towards compat, but at the moment there aren't any stable libs that would fill my use case. (If you know of a different one though, let me know!) But, I am open to other suggestions as to how to make my recipe more compatible.

(As for your other suggestions, the recipe outputs on the left for the reasons you said - any 8 blocks, and nbt doesn't matter as much. You can also batch craft multiple tiers instead of having to replace the items every time. And, as for the else-ifs, never program while tired. That'll be fixed in the next release :) )

**Comment by supersaiyansubtlety** [comment]
I hadn't heard about NBT craftin being unstable. I use it in my own mod set and haven't had issues, but I haven't exactly stress tested all its features, so I can't really claim its stable.  I'll implement specific support for your custom recipe implementation for now. 

As for the 'every block tag', I was actually thinking of making a lib like that. It would have classes that extend the existing tag types, but instead of tags being made from json, they'd just each have an instanceof check. There'd be tags like 'all_blocks', 'all_block_items', 'all_stair_blocks', etc. Do you think this sort of lib would be useful to other devs? Would you find it useful? 

Fair enough on the returning things to the crafting grid, it's definitely more convenient in some scenarios. Though I do wonder what happens if there's a max flame-resistance and if so, what happens if a block that has that max is crafted with the Cementitious Blend?

And yeah, I've definitely looked at my own code and wondered how I'd ever thought it was a good idea : )

**Comment by marshoepial** [comment]
Thanks for understanding. I might have heard wrong about the NBT crafting, I might toy around with it in a different branch at some point. I'd definitely find a 'every block tag' lib super useful personally. I can't vouch for other modders but I can think of a lot of use cases where that would be handy. Also, the recipe won't say it matches when it hits that upper limit of fireproofing. Again, thanks for the suggestion, and I'll definitely look into it once I can play around with Crafting nbt and some sort of lib that has an "anything" item tag. If you run into any issues adding compat let me know!

**Comment by supersaiyansubtlety** [comment]
Well that's embarrassing...

Turns out the fact that you implemented `CraftingRecipe` _should_ have made it work with automated crafting, I just didn't notice that `CraftingRecipe.getRemainingStacks` was a thing... I was calling `ItemStack.getRecipeRemainder` myself and basically re-implementing the default `getRemainingStacks` method. Oopsy.
